### ISSUE TITLE
Improve mapx landing page

### ISSUE THREAD

**Issue by PierreLacroix** [fxi/map-x-landing#1]
Suggested by Pauliina/Pierre 27.02.2016
- [x] Revised text is available at: https://www.dropbox.com/home/MAP-X/Developments/webpage?preview=MAP-X+landing+page.docx 
- [x] Change ~~'Espagno'~~ 'Spanish' to 'Español'
- [x]  At the bottom of the page, above the physical address, add UNEP/GRID-Geneva, as we don't have a "MAP-X office". 
- [x] Typo: Chemin des Anémones (plural)
- [x] Add a link to the brochure: https://www.dropbox.com/home/MAP-X/meetings/4.%20Lima%2C%20Peru%2C%20February%202016/brochure?preview=MAP-X+brochure+web+final.pdf 
(republish the brochure somewhere else than in the dropbox: some people at UN heva issues accessing dropboxes)
- [x]  Add one section on ~~communication~~ _Contact_ with a link to the Youtube channel and a link to http://www.globalpolicyjournal.com/blog/24/02/2016/reports-results-unlocking-big-data-through-geographical-information-systems-extracti

**Comment by PierreLacroix** [comment]
Add the tentative logo

**Comment by PierreLacroix** [comment]
Link between each video and the Youtube one with an option for download
https://www.youtube.com/channel/UC4mnadyjQ78xF8ceGka1LEA

**Comment by NikosAlexandris** [comment]
Linking to YouTube videos done (see https://github.com/fxi/map-x-landing/issues/3). Please, re-open issue (or file a new one if necessary).
